name: "Create new release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version you want to release.'
        required: true

jobs:
  create-new-release:
    name: "Create a new release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draft new release
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-version: ${{ github.event.inputs.version }}
          origin-branch: develop
          target-branch: main
          as-draft: false
          pr-template: |
            ## Motivo da mudança

            Preencha o motivo da mudança.